{% set version = "0.13.2" %}
{% set name = "easydev" %}
{% set sha256 = "a5c054dbf14e923927874fec304de9d988e19c4174cd10bd671ab7a21004098c" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --no-cache-dir -vvv
  entry_points:
    - browse=easydev.browser:main

requirements:
  host:
    - python >=3.8
    - pip
    - poetry-core
  run:
    - python >=3.8
    - colorama
    - pexpect
    - colorlog
    - platformdirs >=4.2.0
    - line_profiler >=4.1.2

test:
  imports:
    - easydev

about:
  home: "https://github.com/cokelaer/easydev"
  license: "BSD-3-Clause"
  license_family: BSD
  license_file: COPYING
  summary: "Common utilities to ease the development of Python packages."
  doc_url: "https://easydev-python.readthedocs.io/en/latest"
  dev_url: "https://github.com/cokelaer/easydev"

extra:
  recipe-maintainers:
    - cokelaer
