{% set version = "0.13.0" %}
{% set name = "easydev" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1ba035f4f7e713cd26c0a7caaf14dae833e81135a57252d46f204cb60c4b8ca9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - browse=easydev.browser:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools

  run:
    - python >={{ python_min }}
    - setuptools
    - colorama
    - pexpect
    - colorlog

test:
  imports:
    - easydev
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: http://packages.python.org/easydev/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: Common utilities to ease the development of Python packages
  doc_url: http://easydev-python.readthedocs.io/en/latest/
  dev_url: https://github.com/cokelaer/easydev

extra:
  recipe-maintainers:
    - cokelaer
