{% set version = "0.11.0" %}
{% set name = "easydev" %}
{% set sha256 = "8402a49e2e9e55b220e52516f92244b5bc3dd438230b183d0c9c0b8b85867a1c" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - easydev_buildPackage=easydev.package:buildPackage
    - multigit=easydev.multigit:main_func
    - browse=easydev.browser:main
    - ibrowse=easydev.browser:main

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - setuptools
    - colorama
    - pexpect
    - colorlog

test:
  imports:
    - easydev
    - easydev.progressbar

about:
  home: http://packages.python.org/easydev/
  license: BSD 3-Clause
  license_family: BSD
  license_file: COPYING
  summary: Common utilities to ease the development of Python packages
  doc_url: http://easydev-python.readthedocs.io/en/latest/
  dev_url: https://github.com/cokelaer/easydev

extra:
  recipe-maintainers:
    - cokelaer
