{% set name = "easydev" %}
{% set version = "0.12.1" %}
{% set sha256 = "b47b7e6f75316ac9045b46487930e16ddb567f3899310deee11d72d8e1f0a231" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/easydev-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation
  entry_points:
    - browse=easydev.browser:main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - colorama
    - pexpect
    - colorlog

test:
  imports:
    - easydev
  commands:
    - browse --help

about:
  home: https://packages.python.org/easydev/
  summary: Common utilities to ease the development of Python packages
  doc_url: https://easydev-python.readthedocs.io/en/latest/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  dev_url: https://github.com/cokelaer/easydev

extra:
  recipe-maintainers:
    - cokelaer
    - mencian
