{% set version = "0.12.1" %}
{% set name = "easydev" %}
{% set sha256 = "b47b7e6f75316ac9045b46487930e16ddb567f3899310deee11d72d8e1f0a231" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - browse=easydev.browser:main

requirements:
  host:
    - pip
    - python
    - python >=3.7
    - setuptools

  run:
    - python
    - python >=3.7
    - setuptools
    - colorama
    - pexpect
    - colorlog

test:
  imports:
    - easydev

about:
  home: http://packages.python.org/easydev/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: Common utilities to ease the development of Python packages
  doc_url: http://easydev-python.readthedocs.io/en/latest/
  dev_url: https://github.com/cokelaer/easydev

extra:
  recipe-maintainers:
    - cokelaer
