travis:
  secure:
    BINSTAR_TOKEN: sn1HBlqyxNrBh+8mWz28wuEhOs88iWLQKbkzj6VM6Nc7luE30g9JZMnn3rxco3uc5GKg1sx3E+E2amVgcTlSplP5I6NHQQgP0cFdNnQna1UTxBRrfgF+20/MFS0Ftoc94FEqdAZda66NU3FZulwmLA8OXj3POAeVJfShFhgplhvbOejSdherobfMagPibJsaYAG829K+rwe9ZMjkaR5c58uNmiMRKv4EBhCeoMT0X7B9c0AbwNdJoAULc6PPANYSI3+2wQ2LDXyyz1NKZ7YHyATUw46aAjyVP2xHtC2qzFaiquttB8F1ODnnMMXGJEhGLP1Duno9u7gwxe1u/lb4+qzuFEdqY635oAnd5I3fGaQbZghAEtChrESNXVl0KLkbOBjzuAIP+pqSd674vKVMSRS1BK73klE+zv6IiMFu1VwPilobFDMwdNB+A6ZtwfgXi1pfobAGxEH050zsMbJzy8Kz8HIVPmi8dAssewMNFx5aXnVjErKjZCAwoCSwjwTZsgK/SR+yDOgdX4TCcfLwTWJrNyNsXrX9g+JqO0T40W76K3SgIYwszG7dQmtoxKOn7QpRNfwCNIPHQjo0JQ0jcEOv1pFsP02sTpDnuNR+wrz5GSJLcz1oeywFUX13+gvqFlCipqSyYxdl2eIiZf9bI1NDg+DU2HKH7Ha1BVZDK0E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
