travis:
  secure:
    BINSTAR_TOKEN: YK5kFIs1c1JlVr28Xl4dDX/+a2JR2O0QVjrPb9vsAABH2ndllIGMavA3ma4xIdNsYtNKOKCDGfDnSNEW7R+SmZuEKWwFWHrzcqK9/gmSMhPpSxOAygc0Dy5DJC6rM5pwm0r55p5bUrGwO86uJNdbICztuHba8q2E5Y8HeQZRU77uloaf+4PhKZRUKdAuzgDcDOxTVo5aGDsb+71+BOszxpR7nxhWWVdejsrszmeiIAu75q0C6Q0wVE4eMJrc/pCISUtXY2X52i8KK8MEOAk7iqIccJ2IFQTf8Z8by8zF54aakWFFaxtNdhV1tUPvqrTngsP3jPgINSL2Ch90erJVOBdzWSkjasQvSVckIKMX3axxzmAwzAdf6xjH3MN+LkeDfgLdTkzWzcxH0YT3GPN/m+iM/56I3YfeYiylZcqAYYv1HSHIiUxoSvcWpIAwzzSNC4Euu8ETwd1ijzjh0uWo4TDijmd00DtqCKzwXW8NDenFSFs+vDy7Um/xm7lIIVN76WcNmcSGag8Ei/u3+gGuIZOaTzOTpEN+f0IilU71AViTBEZFmWF6WShllhfX2Ey23porFK8F4p4g5BOHgizCMMUtuqmZ0gspI+VuPGuYKZAL76S0CyARsaXYhIE9rJK18eZ46MCnyOQ8FwHs77lU7QKAxeDKYNJhgqzCVNfy400=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
